In [1]:
import pandas as pd  #library for handling data (tables like Excel)
import numpy as np  # used for numerical operations

In [ ]:
# Load the Iris dataset from local CSV file into a pandas DataFrame
df = pd.read_csv("Iris.csv")
#url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

# Display first 5 rows of the dataset to verify it loaded correctly
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.shape      # returns (rows, columns) → tells size of dataset

(150, 6)

In [6]:

df.columns    # returns list of column names → shows all features in dataset

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='str')

In [ ]:
df.isnull().sum()

df.dropna(inplace=True)

#isnull() → checks if value is missing
#sum() → counts missing values

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df.describe()

#provides summary statistics like count, mean, standard deviation, minimum, maximum, and quartiles for numerical columns in the dataset.”

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [12]:
df.dtypes   # shows data types of each column

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species              str
dtype: object

In [ ]:
df['Species'] = df['Species'].astype('category')  # convert text to category for memory and performance optimization

#category is a datatype in pandas.
#“Category datatype is used when a column has limited repeated values. Instead of storing full strings repeatedly, 
# it stores them as numerical codes internally, which reduces memory usage and improves performance.”

In [ ]:
df.dtypes   # shows data types of each column

Id                  int64
SepalLengthCm     float64
SepalWidthCm      float64
PetalLengthCm     float64
PetalWidthCm      float64
Species          category
dtype: object

In [ ]:
#“Normalization is a preprocessing technique used to scale numerical data into a fixed range (usually 0 to 1) so that all features contribute equally. It is mainly used in machine learning when features have different ranges.”

numeric_columns = df.select_dtypes(include=['float64']).columns
df_normalized = df.copy()


for col in numeric_columns:
    df_normalized[col] = (df[col] - df[col].min()) / (df[col].max() - df[col].min())


print("\nFirst 5 rows after Normalization:")
df_normalized.head()


# drawback of min max normalization-->It is sensitive to outliers. A single massive outlier can skew the scaled data into a very small range.
#Purpose: Essential for machine learning algorithms that rely on distance metrics

First 5 rows after Normalization:

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1       0.222222      0.625000       0.067797      0.041667  Iris-setosa
1   2       0.166667      0.416667       0.067797      0.041667  Iris-setosa
2   3       0.111111      0.500000       0.050847      0.041667  Iris-setosa
3   4       0.083333      0.458333       0.084746      0.041667  Iris-setosa
4   5       0.194444      0.666667       0.067797      0.041667  Iris-setosa

In [17]:
df.dtypes

Id                  int64
SepalLengthCm     float64
SepalWidthCm      float64
PetalLengthCm     float64
PetalWidthCm      float64
Species          category
dtype: object

In [ ]:
# 8. Convert Categorical to Quantitative (Encoding)
df_encoded = pd.get_dummies(df, columns=['Species'])  # It creates new columns for each category of Species,where each category is represented by 1 or 0, making the data suitable for machine learning algorithms.

print("\nFirst 5 rows after One-Hot Encoding:")

df_encoded.head()

#Converts categorical/text data into numerical format.
#Creates separate binary columns.

#One-Hot Encoding?: Technique that converts categories into binary columns containing 0 and 1.

First 5 rows after One-Hot Encoding:

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species_Iris-setosa,Species_Iris-versicolor,Species_Iris-virginica
0,1,5.1,3.5,1.4,0.2,True,False,False
1,2,4.9,3.0,1.4,0.2,True,False,False
2,3,4.7,3.2,1.3,0.2,True,False,False
3,4,4.6,3.1,1.5,0.2,True,False,False
4,5,5.0,3.6,1.4,0.2,True,False,False